changes in workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,12 +35,12 @@ jobs:
     - name: Terraform Plan
       id: plan
       run: terraform -chdir=terraform/ plan -detailed-exitcode -no-color
-      continue-on-error: true
+    #   continue-on-error: true
+    #
+    # - name: Check for changes
+    #   if: steps.plan.outcome == 'failure' && steps.plan.conclusion == 'failure'
+    #   run: exit 1
 
-    - name: Check for changes
-      if: steps.plan.outcome == 'failure' && steps.plan.conclusion == 'failure'
-      run: exit 1
-        
   build-app:
     runs-on: ubuntu-latest
     
